### ISSUE TITLE
I download this i thought this was the launcher and server?

### ISSUE THREAD

**Issue by neil501** [justemutarkov/EmuTarkov-Launcher#1]
I download this as it was labeled both launcher and server but there are no real files on here nothing for me to run to start the game this might as well be garbage! This was a total waste of my time! Where is the game??? the launcher? I guess to other dont waste your time nothing here to use to run the game

**Comment by neil501** [comment]
i download the game from an actual game site and added their stuff in game doesnt work at all! teels me that battle eye didnt start so it wont let me play i start battle eye then it tells me it cant find host yeah real great for a supposed easy single player game! id be very wary only a small group seems to be able to play this i asked most tell me no they couldnt play

**Comment by SergeyBakinskiy** [comment]
Do not duplicate requests.
